### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ramack** [zeusbaba/gravatar-for-android#2]
Is this project dead? Otherwise it would be great to see it on f-droid, such that can be easily installed and tried out.

**Comment by taweesakteejantuk66** [comment]
Ddd จ่มว่ว้าว

**Comment by 14hooligan88** [comment]
WordPress - 12.0 - Version code: 695
Android device name: Philips X818

01 - [Apr-01 16:50 UTILS] WordPress.onCreate
02 - [Apr-01 16:50 API] Dispatching action: ListAction-REMOVE_EXPIRED_LISTS
03 - [Apr-01 16:50 UTILS] App comes from background
04 - [Apr-01 16:50 STATS] 🔵 Tracked: application_opened
05 - [Apr-01 16:50 API] Dispatching action: SiteAction-FETCH_SITES
06 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCH_SUBSCRIPTIONS
07 - [Apr-01 16:50 API] Dispatching action: SiteAction-FETCH_SITE
08 - [Apr-01 16:50 UTILS] Deferred Initialisation
09 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCH_ACCOUNT
10 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCH_SETTINGS
11 - [Apr-01 16:50 STATS] Number of old stats deleted : 0
12 - [Apr-01 16:50 UTILS] Connection status changed, isConnected=true
13 - [Apr-01 16:50 NOTIFS] notifications update service > created
14 - [Apr-01 16:50 SUPPORT] Zendesk push notifications successfully enabled!
15 - [Apr-01 16:50 NOTIFS] notifications update service > completed
16 - [Apr-01 16:50 NOTIFS] notifications update service > all tasks completed
17 - [Apr-01 16:50 NOTIFS] notifications update service > destroyed
18 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
19 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCHED_SETTINGS
20 - [Apr-01 16:50 API] Dispatching action: SiteAction-UPDATE_SITE
21 - [Apr-01 16:50 DB] Site found by SITE_ID: 160489026
22 - [Apr-01 16:50 DB] Updating site: https://wild7807atmailru.wordpress.com
23 - [Apr-01 16:50 API] Dispatching action: SiteAction-FETCHED_SITES
24 - [Apr-01 16:50 DB] Site found by SITE_ID: 160489026
25 - [Apr-01 16:50 DB] Updating site: https://wild7807atmailru.wordpress.com
26 - [Apr-01 16:50 API] Dispatching action: AccountAction-FETCHED_SUBSCRIPTIONS
27 - [Apr-01 16:51 API] Dispatching action: SiteAction-FETCH_WPCOM_SITE_BY_URL
28 - [Apr-01 16:51 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/wild7807%40mail.ru/?locale=ru_RU - exception: null
29 - [Apr-01 16:51 API] StackTrace: com.android.volley.ServerError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

30 - [Apr-01 16:51 API] Dispatching action: SiteAction-FETCHED_WPCOM_SITE_BY_URL
31 - [Apr-01 16:51 API] Dispatching action: AuthenticationAction-DISCOVER_ENDPOINT
32 - [Apr-01 16:51 NUX] Calling system.listMethods on the following URLs: [https://wild7807@mail.ru/xmlrpc.php, http://wild7807@mail.ru/xmlrpc.php, https://wild7807@mail.ru, http://wild7807@mail.ru, wild7807@mail.ru]
33 - [Apr-01 16:51 NUX] Trying system.listMethods on the following URL: https://wild7807@mail.ru/xmlrpc.php
34 - [Apr-01 16:51 API] Can't deserialize XMLRPC response - exception: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
35 - [Apr-01 16:51 API] StackTrace: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)

36 - [Apr-01 16:51 API] Volley error on https://wild7807@mail.ru/xmlrpc.php - exception: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
37 - [Apr-01 16:51 API] StackTrace: com.android.volley.ParseError: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:72)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	... 1 more

38 - [Apr-01 16:51 API] Receiving OnUnexpectedError event, message: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@df72050) 
39 - [Apr-01 16:51 NUX] The response of system.listMethods was empty for https://wild7807@mail.ru/xmlrpc.php
40 - [Apr-01 16:51 NUX] Trying system.listMethods on the following URL: http://wild7807@mail.ru/xmlrpc.php
41 - [Apr-01 16:51 API] Can't deserialize XMLRPC response - exception: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
42 - [Apr-01 16:51 API] StackTrace: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)

43 - [Apr-01 16:51 API] Volley error on http://wild7807@mail.ru/xmlrpc.php - exception: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
44 - [Apr-01 16:51 API] StackTrace: com.android.volley.ParseError: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:72)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	... 1 more

45 - [Apr-01 16:51 API] Receiving OnUnexpectedError event, message: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@eb5f17c) 
46 - [Apr-01 16:51 NUX] The response of system.listMethods was empty for http://wild7807@mail.ru/xmlrpc.php
47 - [Apr-01 16:51 NUX] Trying system.listMethods on the following URL: https://wild7807@mail.ru
48 - [Apr-01 16:51 API] Can't deserialize XMLRPC response - exception: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
49 - [Apr-01 16:51 API] StackTrace: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)

50 - [Apr-01 16:51 API] Volley error on https://wild7807@mail.ru - exception: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
51 - [Apr-01 16:51 API] StackTrace: com.android.volley.ParseError: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:72)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	... 1 more

52 - [Apr-01 16:51 API] Receiving OnUnexpectedError event, message: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@42ea968) 
53 - [Apr-01 16:51 NUX] The response of system.listMethods was empty for https://wild7807@mail.ru
54 - [Apr-01 16:51 NUX] Trying system.listMethods on the following URL: http://wild7807@mail.ru
55 - [Apr-01 16:51 API] Can't deserialize XMLRPC response - exception: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
56 - [Apr-01 16:51 API] StackTrace: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)

57 - [Apr-01 16:51 API] Volley error on http://wild7807@mail.ru - exception: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
58 - [Apr-01 16:51 API] StackTrace: com.android.volley.ParseError: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:72)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2050)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLSerializerUtils.deserialize(XMLSerializerUtils.java:63)
	at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.parseNetworkResponse(XMLRPCRequest.java:61)
	... 1 more

59 - [Apr-01 16:51 API] Receiving OnUnexpectedError event, message: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:127 in java.io.InputStreamReader@bf8f414) 
60 - [Apr-01 16:51 NUX] The response of system.listMethods was empty for http://wild7807@mail.ru
61 - [Apr-01 16:51 NUX] Invalid URL: wild7807@mail.ru
62 - [Apr-01 16:51 NUX] system.listMethods failed for wild7807@mail.ru - exception: null
63 - [Apr-01 16:51 NUX] StackTrace: org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder$DiscoveryException
	at org.wordpress.android.fluxc.network.discovery.DiscoveryXMLRPCClient.listMethods(DiscoveryXMLRPCClient.java:77)
	at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.checkXMLRPCEndpointValidity(SelfHostedEndpointFinder.java:317)
	at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.verifyXMLRPCUrl(SelfHostedEndpointFinder.java:163)
	at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.verifyOrDiscoverXMLRPCEndpoint(SelfHostedEndpointFinder.java:109)
	at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.access$100(SelfHostedEndpointFinder.java:22)
	at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder$1.run(SelfHostedEndpointFinder.java:84)
	at java.lang.Thread.run(Thread.java:761)

64 - [Apr-01 16:51 NUX] The XML-RPC endpoint was not found by using our 'smart' cleaning approach. Time to start the Endpoint discovery process
65 - [Apr-01 16:51 NUX] Running RSD discovery process on the following URLs: [wild7807@mail.ru, https://wild7807@mail.ru, http://wild7807@mail.ru]
66 - [Apr-01 16:51 NUX] Downloading the HTML content at the following URL: https://wild7807@mail.ru
67 - [Apr-01 16:51 NUX] Can't find the RSD endpoint in the HTML document. Try to check the pingback tag, and the apiLink tag.
68 - [Apr-01 16:51 NUX] XML-RPC endpoint not found
69 - [Apr-01 16:51 NUX] Downloading the HTML content at the following URL: http://wild7807@mail.ru
70 - [Apr-01 16:51 NUX] Can't find the RSD endpoint in the HTML document. Try to check the pingback tag, and the apiLink tag.
71 - [Apr-01 16:51 NUX] XML-RPC endpoint not found
72 - [Apr-01 16:51 API] Dispatching action: AuthenticationAction-DISCOVERY_RESULT
73 - [Apr-01 16:51 STATS] 🔵 Tracked: login_failed_to_login, Properties: {"error_type":"NO_SITE_ERROR","error_context":"OnDiscoveryResponse","error_description":"NO_SITE_ERROR"}
74 - [Apr-01 16:51 API] onDiscoveryResponse has error: NO_SITE_ERROR - NO_SITE_ERROR
75 - [Apr-01 16:51 UTILS] trackLastActivity, activityId: Help Screen
76 - [Apr-01 16:52 UTILS] trackLastActivity, activityId: Help Screen

**Comment by 07tedangnguyen** [comment]
VIỆT NAM

**Comment by ZimZim9** [comment]
Duplicate of #2

**Comment by ZimZim9** [comment]
0xD4D14e59F6a681dFe5a2E89e04ed7CcB1BBBd6c5

**Comment by zeusbaba** [comment]
Unfortunately, i has been a long time since... This project has been in a limbo state. 
Nevertheless, not much has changed with Gravatar API. 

Recently, I published [flutter_gravatar](https://pub.dev/packages/flutter_gravatar) package which is more up2date for Flutter/Dart developers
